const allWords = [
    { word: 'accurate', definition: 'free from mistakes' },
    { word: 'alternatively', definition: 'differently' },
    { word: 'base on', definition: 'to form an idea or opinion from specific information' },
    { word: 'benefit', definition: 'to be good for' },
    { word: 'face', definition: 'to deal with something difficult' },
    { word: 'frequently', definition: 'often' },
    { word: 'identify', definition: 'to recognize' },
    { word: 'image', definition: 'a picture' },
    { word: 'record', definition: 'to take note of and store information' },
    { word: 'unique', definition: 'special; one-of-a-kind' },
    { word: 'attempt', definition: '～を試みる' },
    { word: 'aware', definition: '知って、気が付いて' },
    { word: 'beverage', definition: '飲み物' },
    { word: 'comfortably', definition: '心地よく、気楽に' },
    { word: 'commute', definition: '通勤' },
    { word: 'concern', definition: '懸念' },
    { word: 'confuse', definition: '～と混同する、～を困惑させる' },
    { word: 'creative', definition: '創造的な、創造力のある' },
    { word: 'describe', definition: '言葉で述べる、描写する' },
    { word: 'equipment', definition: '装置、装備' },
    { word: 'feed', definition: '～に食べ物を与える' },
    { word: 'manufacturer', definition: '製造業者、メーカー' },
    { word: 'nerve', definition: '神経' },
    { word: 'object', definition: '物、目的' },
    { word: 'pattern', definition: 'shape; form' },
    { word: 'professor', definition: '教授' },
    { word: 'pronounce', definition: '発音する' },
    { word: 'reliable', definition: '信頼できる' },
    { word: 'replacement', definition: '置き換え、代用品' },
    { word: 'review', definition: '見直す、（再）検討する' },
    { word: 'specific', definition: '明確な、特定の' },
    { word: 'spending', definition: '支出' },
    { word: 'store', definition: '蓄える、（情報など）をしまっておく' },
    { word: 'throat', definition: 'のど' },
    { word: 'unfortunately', definition: '不運にも、残念ながら' }
];