const allWords = [
    { word: 'allow', definition: 'to permit; to make it possible for something to happen' },
    { word: 'citizen', definition: 'a person who lives in a city or country' },
    { word: 'deeply', definition: 'in an intense or strongly felt way' },
    { word: 'expose', definition: 'to show; to let people experience' },
    { word: 'host', definition: 'a person who has or entertains guests' },
    { word: 'interact', definition: 'to talk or do things with other people' },
    { word: 'involve', definition: 'to have or include as part of something' },
    { word: 'organize', definition: 'to plan or arrange' },
    { word: 'popularity', definition: 'being liked, used, or done by a large number of people' },
    { word: 'relax', definition: 'to rest; to feel calm' },
    { word: 'benefit', definition: '～のためになる、益する' },
    { word: 'book', definition: '予約する' },
    { word: 'capital', definition: '首都' },
    { word: 'climate', definition: '気候' },
    { word: 'concerned', definition: '関心のある、心配そうな' },
    { word: 'craft', definition: '仕事、手工業' },
    { word: 'current', definition: '今の、現時の' },
    { word: 'destination', definition: '目的地' },
    { word: 'educational', definition: '教育的な' },
    { word: 'experiential', definition: 'based on experience' },
    { word: 'experiment', definition: '実験' },
    { word: 'fisherman', definition: '漁師' },
    { word: 'fix', definition: '固定させる、修理する' },
    { word: 'immerse', definition: 'to involve yourself in an activity' },
    { word: 'increasingly', definition: 'ますます、だんだん' },
    { word: 'involve', definition: '巻き込む、参加させる' },
    { word: 'life-long', definition: '一生の' },
    { word: 'link', definition: 'つながり' },
    { word: 'meditate', definition: 'to focus the mind, for spiritual purposes or to relax' },
    { word: 'organic', definition: '有機農法の、有機体の' },
    { word: 'physically', definition: '身体的に、物理的に' },
    { word: 'purpose', definition: '目的' },
    { word: 'receptionist', definition: '受付係' },
    { word: 'scientific', definition: '科学の、科学的な' },
    { word: 'stay in touch', definition: 'to continue to communicate by writing or calling' }
];