const allWords = [
    { word: 'actual', definition: 'real' },
    { word: 'extremely', definition: 'very' },
    { word: 'participant', definition: 'a person in an activity' },
    { word: 'process', definition: 'to deal with; to understand' },
    { word: 'separate', definition: 'to divide' },
    { word: 'signal', definition: 'an action that sends a message' },
    { word: 'stage', definition: 'a particular time in an event' },
    { word: 'theory', definition: 'an idea about why something happens' },
    { word: 'therapy', definition: 'a form of treatment that helps people with problems' },
    { word: 'upsetting', definition: 'causing feelings of sadness or worry' },
    { word: 'active', definition: '活動的な' },
    { word: 'ancient', definition: '古代の' },
    { word: 'astronaut', definition: '宇宙飛行士' },
    { word: 'combine', definition: 'A with B で「AをBと結合させる」' },
    { word: 'deal with', definition: '～を処理する、～を扱う' },
    { word: 'depression', definition: 'うつ病、憂鬱' },
    { word: 'direction', definition: '方向、指示' },
    { word: 'disappointed', definition: '失望した、がっかりした' },
    { word: 'divide', definition: '分ける' },
    { word: 'electrical', definition: '電気の' },
    { word: 'emotion', definition: '感情' },
    { word: 'flag', definition: '～に旗を立てる、～に目印をつける' },
    { word: 'geography', definition: '地理' },
    { word: 'heal', definition: '（疾病を）癒す' },
    { word: 'instance', definition: '段階、例' },
    { word: 'lab', definition: '実験室' },
    { word: 'occasion', definition: '（特定の）時、場合' },
    { word: 'painful', definition: '苦しい、痛ましい' },
    { word: 'purpose', definition: '目的' },
    { word: 'random', definition: 'happening at any time for no reason' },
    { word: 'scan', definition: 'to examine for problems or patterns' },
    { word: 'solution', definition: '解決策' },
    { word: 'treatment', definition: '治療' },
    { word: 'upset', definition: '～の心を乱す' },
    { word: 'useful', definition: '役に立つ' }
];